owfilter: Clear the scene in onDeleteWidget
Fixes an "AttributeError: 'NoneType' object has no attribute 'hide'"
in `PlotItem.updateButtons` due to a surviving ViewBox - PlotItem
cycle which still receives scene events.